<p class="MsoNoSpacing" style="text-align: center; line-height: 200%;" align="center"><span class="markedcontent"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 12.0pt; line-height: 200%; font-family: 'Arial',sans-serif;">Buku Petunjuk Penggunaan Aplikasi (User Manual)</span></strong></span></p>
<p class="MsoNoSpacing" style="text-align: center; line-height: 200%;" align="center"><span class="markedcontent"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 20.0pt; line-height: 200%; font-family: 'Arial',sans-serif;">SISTEM INFORMASI</span></strong></span></p>
<p class="MsoNoSpacing" style="text-align: center; line-height: 200%;" align="center"><span class="markedcontent"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 20.0pt; line-height: 200%; font-family: 'Arial',sans-serif;">PEMELIHARAAN PRASARANA GEDUNG </span></strong></span></p>
<p class="MsoNoSpacing" style="text-align: center; line-height: 200%;" align="center"><span class="markedcontent"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 12.0pt; line-height: 200%; font-family: 'Arial',sans-serif;">&nbsp;</span></strong></span></p>
<p class="MsoNoSpacing" style="text-align: center;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 12.0pt; font-family: 'Arial',sans-serif; mso-no-proof: yes;"><!-- [if gte vml 1]><v:shapetype id="_x0000_t75"
 coordsize="21600,21600" o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe"
 filled="f" stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f eqn="if lineDrawn pixelLineWidth 0"/>
  <v:f eqn="sum @0 1 0"/>
  <v:f eqn="sum 0 0 @1"/>
  <v:f eqn="prod @2 1 2"/>
  <v:f eqn="prod @3 21600 pixelWidth"/>
  <v:f eqn="prod @3 21600 pixelHeight"/>
  <v:f eqn="sum @0 0 1"/>
  <v:f eqn="prod @6 1 2"/>
  <v:f eqn="prod @7 21600 pixelWidth"/>
  <v:f eqn="sum @8 21600 0"/>
  <v:f eqn="prod @7 21600 pixelHeight"/>
  <v:f eqn="sum @10 21600 0"/>
 </v:formulas>
 <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
 <o:lock v:ext="edit" aspectratio="t"/>
</v:shapetype><v:shape id="Picture_x0020_1" o:spid="_x0000_i1025" type="#_x0000_t75"
 style='width:262.5pt;height:262.5pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
  o:title="g20-1"/>
</v:shape><![endif]--><!-- [if !vml]--><img src="../public/manual/logo_sampul.png" alt="Logo BPK" width="360" height="360"><!--[endif]--></span></strong></p>
<p class="MsoNormal"><span style="font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoNormal"><span style="font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoNormal" style="text-align: center;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 20.0pt; mso-bidi-font-size: 22.0pt; font-family: 'Arial',sans-serif;">BADAN PEMERIKSA KEUANGAN</span></strong></p>
<p class="MsoNormal" style="text-align: center;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 20.0pt; mso-bidi-font-size: 22.0pt; font-family: 'Arial',sans-serif;">PERWAKILAN PAPUA BARAT</span></strong></p>
<p class="MsoNormal" style="text-align: center;" align="center"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 20.0pt; mso-bidi-font-size: 22.0pt; font-family: 'Arial',sans-serif;">2022</span></strong></p>
<p class="MsoNormal" style="text-align: center;" align="center">&nbsp;</p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: .25in; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l5 level1 lfo1;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">PENDAHULUAN</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;</span>Tujuan Pembuatan Dokumen</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Dokumen user manual Aplikasi Sistem Informasi Pemeliharaan Prasarana Gedung ini dibuat untuk tujuan menggambarkan dan menjelaskan penggunaan aplikasi<span style="mso-spacerun: yes;">&nbsp; </span>untuk admin, User dan Teknisi.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.2<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;</span>Deskripsi Umum Sistem</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Sistem Informasi Pemeliharaan Prasarana Gedung ini membuat admin dapat menginput jadwal pemeliharaan rutin sehingga teknisi dapat melakukan pemeliharaan berdasarkan jadwal tersebut, <em style="mso-bidi-font-style: normal;">user </em>pun dapat melaporkan kerusakan yang terjadi, sehingga teknisi dapat mengetahui bahwa telah terjadi kerusakan dan memperbaiki kerusakan tersebut.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: .25in; mso-add-space: auto; line-height: 150%;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: .25in; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">PERANGKAT YANG DIBUTUHKAN</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.1<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Perangkat<span style="mso-spacerun: yes;">&nbsp; </span>Lunak</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp; </span>Perangkat lunak yang dibutuhkan adalah :</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l3 level1 lfo3;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Windows sebagai <em style="mso-bidi-font-style: normal;">Operating System</em>;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l3 level1 lfo3;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">MySql sebagai <em style="mso-bidi-font-style: normal;">database</em>;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l3 level1 lfo3;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Apache sebagai <em style="mso-bidi-font-style: normal;">PHP Server</em>;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l3 level1 lfo3;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Mozilla Firefox sebagai <em style="mso-bidi-font-style: normal;">Web Browser</em>;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 39.0pt; mso-add-space: auto; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.2<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;</span>Perangkat Keras</span></strong></p>
<p class="MsoNormal" style="margin-left: 45.0pt;"><span style="font-size: 12.0pt; font-family: 'Arial',sans-serif;">Perangkat lunak yang dibutuhkan adalah :</span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 63.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l4 level1 lfo4;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Komputer dengan spesifikasi prosesor Intel(R) Core&trade; i5-3210M CPU @ 2.5 GHz RAM : 8GB;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l4 level1 lfo4;"><!-- [if !supportLists]--><span class="markedcontent"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></span><!--[endif]--><span class="markedcontent"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Mouse sebagai peralatan antarmuka;</span></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l4 level1 lfo4;"><!-- [if !supportLists]--><span class="markedcontent"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></span><!--[endif]--><span class="markedcontent"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Monitor sebagai peralatan antarmuka;</span></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 63.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l4 level1 lfo4;"><!-- [if !supportLists]--><span class="markedcontent"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span></span><!--[endif]--><span class="markedcontent"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Keyboard sebagai peralatan antarmuka;</span></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.3<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;</span></span><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Pengguna Aplikasi</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Adapun yang dapat menggunakan aplikasi ini yaitu :</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo5;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Admin, sebagai orang yang bertanggung jawab dalam pemeliharaan gedung</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo5;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Teknisi, sebagai orang yang melakukan pemeliharaan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-align: justify; text-indent: -.25in; line-height: 150%; mso-list: l1 level1 lfo5;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">User, orang yang memberikan laporan terhadap kerusakan yang terjadi</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: .25in; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l0 level1 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">MENU DAN CARA PENGGUNAAN</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.1<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;</span>Struktur Menu</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Adapun struktur menu pada Aplikasi Sistem Informasi Pemeliharaan Prasarana Gedung adalah sebagai berikut :</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Menu Dashboard;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">2.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Data Master;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Kategori;</span></p>
<p class="MsoListParagraph" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l0 level2 lfo1;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Subkategori;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Gedung;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Ruangan;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><em style="mso-bidi-font-style: normal;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Item</span></em><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">;</span><!-- [if !supportLists]--></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Pekerjaan Rutin;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Jadwal Rutin;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Jadwal Rutin;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Lihat Jadwal Rutin;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">4.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Perbaikan;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Permintaan Perbaikan;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Status Perbaikan;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">5.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Admin;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Kelola User;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 93.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level2 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: Symbol; mso-fareast-font-family: Symbol; mso-bidi-font-family: Symbol;"><span style="mso-list: Ignore;">&middot;<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Hak Akses;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">6.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Report;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 57.0pt; mso-add-space: auto; text-indent: -.25in; line-height: 150%; mso-list: l2 level1 lfo6;"><!-- [if !supportLists]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">7.<span style="font: 7.0pt 'Times New Roman';">&nbsp;&nbsp;&nbsp; </span></span></span><!--[endif]--><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Logout;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-indent: -21.0pt; line-height: 150%; mso-list: l0 level2 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.2<span style="font: 7.0pt 'Times New Roman';"> </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><span style="mso-spacerun: yes;">&nbsp;</span>Penggunaan</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Pada bagian ini akan dijelaskan mengenai tata cara pengisian data master, penginputan jadwal rutin, mengubah status pada jadwal rutin, pelaporan kerusakan, mengubah status pada laporan kerusakan, input user baru, hak akses user, serta laporan.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 39.0pt; mso-add-space: auto; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo2;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">3.2.1<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Membuka Aplikasi</span></strong></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk memulai aplikasi bukalah <em style="mso-bidi-font-style: normal;">web browser</em> dengan alamat: localhost/spg, akan muncul halaman login sebagai berikut:</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1in; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"><img style="display: block; margin-left: auto; margin-right: auto;" src="../public/manual/halaman_login.png" alt="Halaman Login" width="1061" height="534"></span></p>
<p class="MsoListParagraph" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman login</span></p>
<p class="MsoListParagraph" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Masukkan <em style="mso-bidi-font-style: normal;">User</em> dan <em style="mso-bidi-font-style: normal;">Password</em>, sebagai contoh User : admin dengan password : contoh123. Setelah dimasukkan dengan benar, klik tombol <em style="mso-bidi-font-style: normal;">Login</em> atau tekan tombol Enter pada <em style="mso-bidi-font-style: normal;">keyboard</em>. Apabila <em style="mso-bidi-font-style: normal;">user</em> dan <em style="mso-bidi-font-style: normal;">password</em> benar maka akan tampil halaman <em style="mso-bidi-font-style: normal;">dashboard</em>.</span></p>
<p class="MsoNormal">&nbsp;</p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo1;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1.1<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Dashboard</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-no-proof: yes;"><!-- [if gte vml 1]><v:shapetype
 id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t"
 path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f eqn="if lineDrawn pixelLineWidth 0"/>
  <v:f eqn="sum @0 1 0"/>
  <v:f eqn="sum 0 0 @1"/>
  <v:f eqn="prod @2 1 2"/>
  <v:f eqn="prod @3 21600 pixelWidth"/>
  <v:f eqn="prod @3 21600 pixelHeight"/>
  <v:f eqn="sum @0 0 1"/>
  <v:f eqn="prod @6 1 2"/>
  <v:f eqn="prod @7 21600 pixelWidth"/>
  <v:f eqn="sum @8 21600 0"/>
  <v:f eqn="prod @7 21600 pixelHeight"/>
  <v:f eqn="sum @10 21600 0"/>
 </v:formulas>
 <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
 <o:lock v:ext="edit" aspectratio="t"/>
</v:shapetype><v:shape id="Picture_x0020_3" o:spid="_x0000_i1026" type="#_x0000_t75"
 style='width:298.5pt;height:150pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
  o:title=""/>
</v:shape><![endif]--><!-- [if !vml]--><img style="display: block; margin-left: auto; margin-right: auto;" src="../public/manual/Dashboard.png" alt="Dashboard" width="1068" height="538"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0in; line-height: 150%; text-align: center;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Dashboard</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><!-- [if gte vml 1]><v:shape id="Picture_x0020_4" o:spid="_x0000_i1025"
 type="#_x0000_t75" style='width:106.5pt;height:189pt;visibility:visible;
 mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
  o:title="" croptop="8008f" cropbottom="17494f" cropleft="-115f" cropright="54360f"/>
</v:shape><![endif]--><!-- [if !vml]--><img src="../public/manual/menu.png" alt="Menu" width="188" height="323"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Daftar Menu</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Pada Halaman <em style="mso-bidi-font-style: normal;">Dashboard</em> terdapat grafik yang menunjukkan jumlah pemeliharaan insidentil dan pemeliharaan rutin yang belum terselesaikan serta grafik pekerjaan insidentil berdasarkan status dan prioritasnya.</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;">&nbsp;</p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo1;"><!-- [if !supportLists]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1.1<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><!--[endif]--><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Data Master</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-no-proof: yes;"><!-- [if gte vml 1]><v:shapetype
 id="_x0000_t75" coordsize="21600,21600" o:spt="75" o:preferrelative="t"
 path="m@4@5l@4@11@9@11@9@5xe" filled="f" stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f eqn="if lineDrawn pixelLineWidth 0"/>
  <v:f eqn="sum @0 1 0"/>
  <v:f eqn="sum 0 0 @1"/>
  <v:f eqn="prod @2 1 2"/>
  <v:f eqn="prod @3 21600 pixelWidth"/>
  <v:f eqn="prod @3 21600 pixelHeight"/>
  <v:f eqn="sum @0 0 1"/>
  <v:f eqn="prod @6 1 2"/>
  <v:f eqn="prod @7 21600 pixelWidth"/>
  <v:f eqn="sum @8 21600 0"/>
  <v:f eqn="prod @7 21600 pixelHeight"/>
  <v:f eqn="sum @10 21600 0"/>
 </v:formulas>
 <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
 <o:lock v:ext="edit" aspectratio="t"/>
</v:shapetype><v:shape id="Picture_x0020_7" o:spid="_x0000_i1027" type="#_x0000_t75"
 style='width:348pt;height:175.5pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
  o:title=""/>
</v:shape><![endif]--><!-- [if !vml]--><img style="display: block; margin-left: auto; margin-right: auto;" src="../public/manual/input_kategori.png" alt="Input Kategori" width="1058" height="533"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><em style="mso-bidi-font-style: normal;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input</span></em><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;"> Kategori</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menginput data kategori silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Kategori&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi kode kategori dan uraian kategori, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><!-- [if gte vml 1]><v:shape id="Picture_x0020_8" o:spid="_x0000_i1026"
 type="#_x0000_t75" style='width:352.5pt;height:177.75pt;visibility:visible;
 mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image003.png"
  o:title=""/>
</v:shape><![endif]--><!-- [if !vml]--><img src="../public/manual/master_kategori.png" alt="Master Kategori" width="1054" height="531"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Master Kategori</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan data langsung tambil pada tabel &ldquo;Master Kategori&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;">&nbsp;</p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-no-proof: yes;"><!-- [if gte vml 1]><v:shapetype id="_x0000_t75" coordsize="21600,21600"
 o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe" filled="f"
 stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f eqn="if lineDrawn pixelLineWidth 0"/>
  <v:f eqn="sum @0 1 0"/>
  <v:f eqn="sum 0 0 @1"/>
  <v:f eqn="prod @2 1 2"/>
  <v:f eqn="prod @3 21600 pixelWidth"/>
  <v:f eqn="prod @3 21600 pixelHeight"/>
  <v:f eqn="sum @0 0 1"/>
  <v:f eqn="prod @6 1 2"/>
  <v:f eqn="prod @7 21600 pixelWidth"/>
  <v:f eqn="sum @8 21600 0"/>
  <v:f eqn="prod @7 21600 pixelHeight"/>
  <v:f eqn="sum @10 21600 0"/>
 </v:formulas>
 <v:path o:extrusionok="f" gradientshapeok="t" o:connecttype="rect"/>
 <o:lock v:ext="edit" aspectratio="t"/>
</v:shapetype><v:shape id="Picture_x0020_22" o:spid="_x0000_i1026" type="#_x0000_t75"
 style='width:344.25pt;height:173.25pt;visibility:visible;mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image001.png"
  o:title="input_subkategori"/>
</v:shape><![endif]--><!-- [if !vml]--><img src="../public/manual/input_subkategori.png" alt="Input Subkategori" width="1053" height="530"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><em style="mso-bidi-font-style: normal;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Subkategori</span></em></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menginput data Subkategori silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Subkategori&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi kategori, kode subkategori dan uraian subkategori, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1in; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-no-proof: yes;"><!-- [if gte vml 1]><v:shape id="Picture_x0020_24" o:spid="_x0000_i1025"
 type="#_x0000_t75" style='width:351.75pt;height:177pt;visibility:visible;
 mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image003.png"
  o:title="master_subkategori"/>
</v:shape><![endif]--><!-- [if !vml]--><img style="display: block; margin-left: auto; margin-right: auto;" src="../public/manual/master_subkategori.png" alt="Master Subkategori" width="1064" height="536"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Master Subkategori</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan data langsung tambil pada tabel &ldquo;Master Kategori&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span><span style="mso-no-proof: yes;"><!-- [if gte vml 1]><v:shape id="Picture_x0020_9" o:spid="_x0000_i1025"
 type="#_x0000_t75" style='width:348pt;height:175.5pt;visibility:visible;
 mso-wrap-style:square'>
 <v:imagedata src="file:///C:/Users/accank/AppData/Local/Temp/msohtmlclip1/01/clip_image005.png"
  o:title=""/>
</v:shape><![endif]--><!-- [if !vml]--><img style="display: block; margin-left: auto; margin-right: auto;" src="../public/manual/input_gedung.png" alt="Input Gedung" width="1050" height="529"><!--[endif]--></span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Gedung</span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menambah data gedung silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Gedung&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi nama gedung dan keterangan, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menambah data ruangan silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Ruangan&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi nama gedung, kode ruangan, uraian ruangan, dan keterangan, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/master_ruangan.png" alt="Master Ruangan" width="1077" height="543"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Master Ruangan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan, data langsung tampil pada tabel &ldquo;Master Ruangan&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/input_item.png" alt="Input Item" width="1058" height="533"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Item</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menambah data item silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Item&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi nama item, merek item, tipe item, dan kategori, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/master_item.png" alt="Master Item" width="1064" height="536"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Master Item</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan, data langsung tampil pada tabel &ldquo;Master Item&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/input_item_ruangan.png" alt="Input Item Ruangan" width="1062" height="535"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Item Ruangan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menambah data item tiap ruangan silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Item Ruangan&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi nama gedung, nama ruangan, nama item, dan tahun pengadaan, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/master_item_ruangan.png" alt="Master Item Ruangan" width="1072" height="540"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Master Item Ruangan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan, data langsung tampil pada tabel &ldquo;Master Item Ruangan&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/input_pekerjaan_rutin.png" alt="Input Pekerjaan Rutin" width="1062" height="535"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Pekerjaan Rutin</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menambah data pekerjaan rutin, silahkan klik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Pekerjaan Rutin&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi jenis pekerjaan, uraian pekerjaan, kategori, dan interval waktu, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/master_pekerjaan_rutin.png" alt="Master Pekerjaan Rutin" width="1058" height="533"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Master Pekerjaan Rutin</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan, data langsung tampil pada tabel &ldquo;Master Pekerjaan Rutin&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;">&nbsp;</p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo1;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1.1<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Jadwal Rutin</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif; mso-no-proof: yes;"><img src="../public/manual/input_jadwal_rutin.png" alt="Input Jadwal Rutin" width="1059" height="534"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Input Jadwal Rutin</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk mengisi jadwal rutin, </span><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">silahkan klik menu &ldquo;Jadwal Rutin&rdquo; pada bagian menu di sebelah kiri, setelah itu Klik &ldquo;Input Jadwal Rutin&rdquo;, lalu tentukan tanggal dan teknisi yang akan mengerjakan, setelah itu klik tombol &ldquo;Buat Draft&rdquo;, lalu silahkan isi nama gedung, nama ruangan, item, dan jenis pekerjaan, kemudian klik tombol &ldquo;Tambah Draft&rdquo;. Pada halamn ini juga terdapat fitur impor jadwal pekerjaan rutin dengan mengisi template yang sudah ada. Download terlebih dahulu template yang telah disediakan, lalu ikuti istruksi pengeisian yang teadapat dalam template, kemudian upload file template yang telah diisi kemudian kik tombol &ldquo;Upload Dokumen&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif; mso-no-proof: yes;"><img src="../public/manual/tabel_input_jadwal_rutin.png" alt="Tabel Input Jadwal Rutin" width="1063" height="536"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Tabel Input Jadwal Rutin</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah itu jadwal akan tersimpan pada tabel draft, jadwal yang ada dapat dihapus satu persatu dengan mengkil tombol &ldquo;Delete&rdquo; pada </span><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">kolom aksi atau bila ingin menghapus semua dapat menekan tombol &ldquo;Hapus Draft&rdquo;. Bila semua jadwal sudah dirasa benar maka untuk menyimpan jadwal tersebut silahkan mengklik tombol &ldquo;Simpan Jadwal&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/jadwal_rutin.png" alt="Jadwal Rutin" width="1068" height="538"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Jadwal Rutin</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Semua jadwal rutin dapat dilihat dengan mengklik menu &ldquo;Data Master&rdquo; pada bagian menu di sebelah kiri, setelah itu klik &ldquo;Lihat Jadwal Rutin&rdquo;. Pada tabel tersebut dapat kita melihat status dari pekerjaan yang telah dijadwalkan, Selesai, On Progress, Pending, Belum Dikerjakan, dan Tidak Dikerjakan. Untuk mengubah status dari pekerjaan rutin bisa dengan mengklik tombol &ldquo;Edit&rdquo; dan untuk menghapus jadwal dengan mengklik tombol &ldquo;Delete&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/update_status_rutin.png" alt="Update Status Rutin" width="1068" height="538"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Update Status Pekerjaan Rutin</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Saat mengubah status pekerjaan, keterangan wajib diisi dan pastikan nama teknisi telah sesuai, setelah itu klik tombol &ldquo;Update Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/approve_status_rutin.png" alt="Approve Status Rutin" width="1073" height="541"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Approve Status Pekerjaan Rutin</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Bila status pekerjaan rutin telah berubah menjadi selesai, maka pada kolom paling kanan pada tabel akan muncul tombol &ldquo;Approve&rdquo;, Setelah admin melakukan pengecekan hasil pekerjaan rutin teknisi dan dirasa sudah baik maka dapat mengklik Setelah admin melakukan pengecekan hasil pekerjaan rutin teknisi dan dirasa sudah baik maka dapat mengklik<span style="mso-spacerun: yes;">&nbsp; </span>tombol &ldquo;Approve&rdquo; tersebut, lalu tekan tombol &ldquo;Ya, Approve&rdquo; dan bila dirasa tidak sesui maka dapat menekan tombol &ldquo;Tolak&rdquo;. Bila ditolak maka status pekerjaan akan kembali menjadi On Progress.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo1;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1.1<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Perbaikan</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/input_laporan_kerusakan.png" alt="Input Laporan Kerusakan" width="1064" height="536"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Input Laporan Kerusakan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk melaporkan kerusakan, </span><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">silahkan klik menu &ldquo;Perbaikan&rdquo; pada bagian menu di sebelah kiri, setelah itu klik &ldquo;Permintaan Perbaikan&rdquo;, lalu tentukan tanggal, gedung, ruangan, item, prioritas dan keluhan, kemudian klik tombol &ldquo;Simpan&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/data_laporan_kerusakan.png" alt="Data Laporan Kerusakan" width="1076" height="542"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Data Laporan Kerusakan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk melihat data laporan kerusakan, silahkan klik menu &ldquo;Perbaikan&rdquo; pada bagian di sebelah kiri, setelah itu klik &ldquo;Status Perbaikan&rdquo;. </span><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk mengubah status dari laporan kerusakan bisa dengan mengklik tombol &ldquo;Edit&rdquo; dan untuk menghapus jadwal dengan mengklik <span style="mso-spacerun: yes;">&nbsp;</span>tombol &ldquo;Delete&rdquo; pada komol paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/update_status_nonrutin.png" alt="Update Status Kerusakan" width="1073" height="541"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 12.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Update Status Laporan Kerusakan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Saat mengubah status pekerjaan, keterangan dan teknisi wajib diisi. Selain status pekerjaan, skala prioritas juga masih dapat diubah pada halaman ini. Setelah itu klik tombol &ldquo;Update Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/approve_status_nonrutin.png" alt="Approve Status Kerusakan" width="1074" height="541"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="font-family: 'Arial',sans-serif;">Approve Status Pekerjaan Kerusakan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 11.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Bila status pekerjaan kerusakan telah berubah menjadi selesai, maka pada kolom paling kanan pada tabel akan muncul tombol &ldquo;Approve&rdquo;. Setelah admin melakukan pengecekan hasil pekerjaan rutin teknisi dan dirasa sudah baik maka dapat mengklik<span style="mso-spacerun: yes;">&nbsp; </span>tombol &ldquo;Approve&rdquo; tersebut, lalu tekan tombol &ldquo;Ya, Approve&rdquo; dan bila dirasa tidak sesui maka dapat menekan tombol &ldquo;Tolak&rdquo;. Bila ditolak maka status pekerjaan akan kembali menjadi On Progress.</span></p>
<p class="MsoNormal"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; font-family: 'Arial',sans-serif;">&nbsp;</span></strong></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo1;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1.2<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Admin</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/input_pengguna.png" alt="Input Pengguna" width="1066" height="537"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Input Pengguna Aplikasi</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menginput pengguna aplikasi silahkan klik menu &ldquo;Admin&rdquo; pada bagian menu di sebelah kiri, setelah itu klik &ldquo;Kelola User&rdquo;, lalu klik tombol &ldquo;Tambah Data&rdquo; pada sudut kanan atas. Silahkan mengisi data pengguna sesuai dengan <em style="mso-bidi-font-style: normal;">form</em> yang ada, kemudian klik tombol &ldquo;Simpan Data&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/data_pengguna.png" alt="Data Pengguna" width="1070" height="539"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Data Pengguna Aplikasi</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah tersimpan, data langsung tampil pada tabel &ldquo;Master Pengguna Aplikasi&rdquo;. Untuk mengedit dan menghapus data, silahkan menekan tombol &ldquo;edit&rdquo; atau &ldquo;hapus&rdquo; pada kolom paling kanan dalam tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/group_akses.png" alt="Group Akses" width="1069" height="539"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Group Akses</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk mengatur <em style="mso-bidi-font-style: normal;">privilege</em> pengguna aplikasi silahkan klik menu &ldquo;Admin&rdquo; pada bagian menu di sebelah kiri, setelah itu klik &ldquo;Hak Akses&rdquo;, lalu klik tombol &ldquo;Edit&rdquo; pada kolom sebelah kanan pada tabel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/hak_akses.png" alt="Hak Akses" width="1064" height="536"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Mengatur Hak Akses</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Silahkan mengaktifkan tanda centang pada menu yang ingin ditampilkan terhadap group user.</span></p>
<p class="MsoListParagraphCxSpFirst" style="margin-left: 1.0in; mso-add-space: auto; text-indent: -.5in; line-height: 150%; mso-list: l0 level3 lfo1;"><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif; mso-fareast-font-family: Arial;"><span style="mso-list: Ignore;">1.1.1<span style="font: 7.0pt 'Times New Roman';">&nbsp; </span></span></span></strong><strong style="mso-bidi-font-weight: normal;"><span style="font-size: 14.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Halaman Pembuatan Laporan</span></strong></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/filter_laporan.png" alt="Filter Laporan" width="1076" height="542"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Filter Laporan</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: justify; line-height: 150%;"><span style="font-size: 12.0pt; mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Untuk menarik laporan dari aplikasi silahkan klik menu &ldquo;Report&rdquo; pada bagian menu di sebelah kiri, setelah itu tentukan Jenis laporan, lalu silahkan melakukan filter baik berdasarkan teknisi, tanggal, dan status. Kemudian klik tombol &ldquo;Cari&rdquo;.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-no-proof: yes;"><img src="../public/manual/laporan.png" alt="Laporan" width="1070" height="539"></span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; text-align: center; line-height: 150%;" align="center"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Hasil Filter Laporan</span></p>
<p class="MsoListParagraphCxSpLast" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">Setelah melakukan filter maka akan tampil laporan yang diinginkan, laporan ini bisa dicetak atau bisa disimpan dalam format PDF atau Excel.</span></p>
<p class="MsoListParagraphCxSpMiddle" style="margin-left: 1.0in; mso-add-space: auto; line-height: 150%;"><span style="mso-bidi-font-size: 22.0pt; line-height: 150%; font-family: 'Arial',sans-serif;">&nbsp;</span><span style="mso-no-proof: yes;"><!-- [if gte vml 1]><v:shapetype id="_x0000_t75" coordsize="21600,21600"
 o:spt="75" o:preferrelative="t" path="m@4@5l@4@11@9@11@9@5xe" filled="f"
 stroked="f">
 <v:stroke joinstyle="miter"/>
 <v:formulas>
  <v:f e                    </body>--></span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>